services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "4000:4000"
    volumes:
      - ./storage:/app/storage
    environment:
      NODE_ENV: production
      PORT: 4000
      # DATABASE_URL: "postgresql://microservices:microservices@postgresql:5432/mscovoitivoire?schema=public"
      DATABASE_URL: "postgresql://microservices:microservices@ms_pg_sql:5432/microservices?schema=public"
      JWT_SECRET: "72f21bf2916454b01dd8"
      JWT_EXPIRE: "7d"
      COOKIE_EXPIRE: "5"
      CLOUDINARY_CLOUD_NAME: "dtakbf3ha"
      CLOUDINARY_API_KEY: "196581248868223"
      CLOUDINARY_API_SECRET: "_IN5L1lB4JNqh-t_csNWSb3z5W0"
      FILE_STORAGE_PATH: "/app/storage"
    networks:
      - microservices-net
    restart: always

networks:
  microservices-net:
    external: true
