version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "4000:4000"
    volumes:
      - ./production.env:/app/.env        # montage du fichier .env modifiable
      - ./storage:/app/storage            # persistance des fichiers uploadés
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://microservices:microservices@postgresql:5432/microservices?schema=public
    networks:
      - microservices-net
    depends_on:
      - postgresql
    restart: always

networks:
  microservices-net:
    external: true

volumes:
  postgres_data:   # tu peux même supprimer ce volume si tu ne gères plus postgres ici
