services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_covoit
    ports:
      - "4000:4000"
    volumes:
      - ./production.env:/app/.env   # monte ton .env local
      - ./storage:/app/storage            # persistance des fichiers uploadés
    environment:
      NODE_ENV: production
    networks:
      - microservices-net
    restart: always

networks:
  microservices-net:
    external: true
